Repository Elisabete-MO/Frontend-E-learning-Platform---Hackathon-ONE, pull requests merged in 2025-09, with the labels that each got.

#43 Feature/pagina inicial
  README.md
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.js
  src/App.jsx
  src/assets/pagina_inicial.png
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Home/Main.jsx
  src/components/StylezedButton.jsx
  src/index.css
  src/logo.svg
  src/pages/Home.jsx
Labels: frontend

#46 Feature/setup eslint
  .eslintrc.json
  .github/workflows/buildtest.yml
  package-lock.json
  package.json
  src/App.jsx
  src/App.test.js
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Home/Main.jsx
  src/components/StylezedButton.jsx
  src/index.js
  src/pages/Home.jsx
  src/reportWebVitals.js
  src/setupTests.js
Labels: enhancement, frontend

#47 chore(eslint):inclui comando lint:fix na Action para verificar padron…
  .github/workflows/buildtest.yml
Labels: frontend

#49 Feature/pagina cadastro
  src/assets/icons/email.svg
  src/assets/icons/lock.svg
  src/assets/icons/user.svg
  src/assets/ilustracao-cadastro.png
  src/components/EstruturalComponents/InputField/InputField.module.css
  src/components/EstruturalComponents/InputField/index.jsx
  src/components/RegisterPage/RegisterBanner/RegisterBanner.module.css
  src/components/RegisterPage/RegisterBanner/index.jsx
  src/components/RegisterPage/RegisterForm/RegisterForm.module.css
  src/components/RegisterPage/RegisterForm/index.jsx
  src/pages/Cadastro.jsx
  src/pages/Home/index.jsx
  src/pages/RegisterPage/RegisterPage.module.css
  src/pages/RegisterPage/index.jsx
Labels: frontend, admin, student, instructor
